import ColumnsProps from "./ColumnsProps";
import classNames from "./Columns.module.scss";

export default function Columns(props: ColumnsProps): JSX.Element {
  const assignedProps = { ...props };
  delete assignedProps["isDirectionRow"];
  delete assignedProps["isDirectionRowReverse"];
  delete assignedProps["isDirectionColumn"];
  delete assignedProps["isDirectionColumnReverse"];
  delete assignedProps["isMobileDirectionRow"];
  delete assignedProps["isMobileOrMoreDirectionRow"];
  delete assignedProps["isTabletOrLessDirectionRow"];
  delete assignedProps["isTabletDirectionRow"];
  delete assignedProps["isTabletOrMoreDirectionRow"];
  delete assignedProps["isDesktopOrLessDirectionRow"];
  delete assignedProps["isDesktopDirectionRow"];
  delete assignedProps["isDesktopOrMoreDirectionRow"];
  delete assignedProps["isWidescreenOrLessDirectionRow"];
  delete assignedProps["isWidescreenDirectionRow"];
  delete assignedProps["isWidescreenOrMoreDirectionRow"];
  delete assignedProps["isFullhdOrLessDirectionRow"];
  delete assignedProps["isFullhdDirectionRow"];
  delete assignedProps["isMobileDirectionRowReverse"];
  delete assignedProps["isMobileOrMoreDirectionRowReverse"];
  delete assignedProps["isTabletOrLessDirectionRowReverse"];
  delete assignedProps["isTabletDirectionRowReverse"];
  delete assignedProps["isTabletOrMoreDirectionRowReverse"];
  delete assignedProps["isDesktopOrLessDirectionRowReverse"];
  delete assignedProps["isDesktopDirectionRowReverse"];
  delete assignedProps["isDesktopOrMoreDirectionRowReverse"];
  delete assignedProps["isWidescreenOrLessDirectionRowReverse"];
  delete assignedProps["isWidescreenDirectionRowReverse"];
  delete assignedProps["isWidescreenOrMoreDirectionRowReverse"];
  delete assignedProps["isFullhdOrLessDirectionRowReverse"];
  delete assignedProps["isFullhdDirectionRowReverse"];
  delete assignedProps["isMobileDirectionColumn"];
  delete assignedProps["isMobileOrMoreDirectionColumn"];
  delete assignedProps["isTabletOrLessDirectionColumn"];
  delete assignedProps["isTabletDirectionColumn"];
  delete assignedProps["isTabletOrMoreDirectionColumn"];
  delete assignedProps["isDesktopOrLessDirectionColumn"];
  delete assignedProps["isDesktopDirectionColumn"];
  delete assignedProps["isDesktopOrMoreDirectionColumn"];
  delete assignedProps["isWidescreenOrLessDirectionColumn"];
  delete assignedProps["isWidescreenDirectionColumn"];
  delete assignedProps["isWidescreenOrMoreDirectionColumn"];
  delete assignedProps["isFullhdOrLessDirectionColumn"];
  delete assignedProps["isFullhdDirectionColumn"];
  delete assignedProps["isMobileDirectionColumnReverse"];
  delete assignedProps["isMobileOrMoreDirectionColumnReverse"];
  delete assignedProps["isTabletOrLessDirectionColumnReverse"];
  delete assignedProps["isTabletDirectionColumnReverse"];
  delete assignedProps["isTabletOrMoreDirectionColumnReverse"];
  delete assignedProps["isDesktopOrLessDirectionColumnReverse"];
  delete assignedProps["isDesktopDirectionColumnReverse"];
  delete assignedProps["isDesktopOrMoreDirectionColumnReverse"];
  delete assignedProps["isWidescreenOrLessDirectionColumnReverse"];
  delete assignedProps["isWidescreenDirectionColumnReverse"];
  delete assignedProps["isWidescreenOrMoreDirectionColumnReverse"];
  delete assignedProps["isFullhdOrLessDirectionColumnReverse"];
  delete assignedProps["isFullhdDirectionColumnReverse"];

  const classNameList = [
    classNames["columns"]
  ];
  props.isDirectionRow && classNameList.push(classNames["is-direction-row"]);
  props.isDirectionRowReverse && classNameList.push(classNames["is-direction-row-reverse"]);
  props.isDirectionColumn && classNameList.push(classNames["is-direction-column"]);
  props.isDirectionColumnReverse && classNameList.push(classNames["is-direction-column-reverse"]);
  props.isMobileDirectionRow && classNameList.push(classNames["is-mobile-direction-row"]);
  props.isMobileOrMoreDirectionRow && classNameList.push(classNames["is-mobile-or-more-direction-row"]);
  props.isTabletOrLessDirectionRow && classNameList.push(classNames["is-tablet-or-less-direction-row"]);
  props.isTabletDirectionRow && classNameList.push(classNames["is-tablet-direction-row"]);
  props.isTabletOrMoreDirectionRow && classNameList.push(classNames["is-tablet-or-more-direction-row"]);
  props.isDesktopOrLessDirectionRow && classNameList.push(classNames["is-desktop-or-less-direction-row"]);
  props.isDesktopDirectionRow && classNameList.push(classNames["is-desktop-direction-row"]);
  props.isDesktopOrMoreDirectionRow && classNameList.push(classNames["is-desktop-or-more-direction-row"]);
  props.isWidescreenOrLessDirectionRow && classNameList.push(classNames["is-widescreen-or-less-direction-row"]);
  props.isWidescreenDirectionRow && classNameList.push(classNames["is-widescreen-direction-row"]);
  props.isWidescreenOrMoreDirectionRow && classNameList.push(classNames["is-widescreen-or-more-direction-row"]);
  props.isFullhdOrLessDirectionRow && classNameList.push(classNames["is-fullhd-or-less-direction-row"]);
  props.isFullhdDirectionRow && classNameList.push(classNames["is-fullhd-direction-row"]);
  props.isMobileDirectionRowReverse && classNameList.push(classNames["is-mobile-direction-row-reverse"]);
  props.isMobileOrMoreDirectionRowReverse && classNameList.push(classNames["is-mobile-or-more-direction-row-reverse"]);
  props.isTabletOrLessDirectionRowReverse && classNameList.push(classNames["is-tablet-or-less-direction-row-reverse"]);
  props.isTabletDirectionRowReverse && classNameList.push(classNames["is-tablet-direction-row-reverse"]);
  props.isTabletOrMoreDirectionRowReverse && classNameList.push(classNames["is-tablet-or-more-direction-row-reverse"]);
  props.isDesktopOrLessDirectionRowReverse && classNameList.push(classNames["is-desktop-or-less-direction-row-reverse"]);
  props.isDesktopDirectionRowReverse && classNameList.push(classNames["is-desktop-direction-row-reverse"]);
  props.isDesktopOrMoreDirectionRowReverse && classNameList.push(classNames["is-desktop-or-more-direction-row-reverse"]);
  props.isWidescreenOrLessDirectionRowReverse && classNameList.push(classNames["is-widescreen-or-less-direction-row-reverse"]);
  props.isWidescreenDirectionRowReverse && classNameList.push(classNames["is-widescreen-direction-row-reverse"]);
  props.isWidescreenOrMoreDirectionRowReverse && classNameList.push(classNames["is-widescreen-or-more-direction-row-reverse"]);
  props.isFullhdOrLessDirectionRowReverse && classNameList.push(classNames["is-fullhd-or-less-direction-row-reverse"]);
  props.isFullhdDirectionRowReverse && classNameList.push(classNames["is-fullhd-direction-row-reverse"]);
  props.isMobileDirectionColumn && classNameList.push(classNames["is-mobile-direction-column"]);
  props.isMobileOrMoreDirectionColumn && classNameList.push(classNames["is-mobile-or-more-direction-column"]);
  props.isTabletOrLessDirectionColumn && classNameList.push(classNames["is-tablet-or-less-direction-column"]);
  props.isTabletDirectionColumn && classNameList.push(classNames["is-tablet-direction-column"]);
  props.isTabletOrMoreDirectionColumn && classNameList.push(classNames["is-tablet-or-more-direction-column"]);
  props.isDesktopOrLessDirectionColumn && classNameList.push(classNames["is-desktop-or-less-direction-column"]);
  props.isDesktopDirectionColumn && classNameList.push(classNames["is-desktop-direction-column"]);
  props.isDesktopOrMoreDirectionColumn && classNameList.push(classNames["is-desktop-or-more-direction-column"]);
  props.isWidescreenOrLessDirectionColumn && classNameList.push(classNames["is-widescreen-or-less-direction-column"]);
  props.isWidescreenDirectionColumn && classNameList.push(classNames["is-widescreen-direction-column"]);
  props.isWidescreenOrMoreDirectionColumn && classNameList.push(classNames["is-widescreen-or-more-direction-column"]);
  props.isFullhdOrLessDirectionColumn && classNameList.push(classNames["is-fullhd-or-less-direction-column"]);
  props.isFullhdDirectionColumn && classNameList.push(classNames["is-fullhd-direction-column"]);
  props.isMobileDirectionColumnReverse && classNameList.push(classNames["is-mobile-direction-column-reverse"]);
  props.isMobileOrMoreDirectionColumnReverse && classNameList.push(classNames["is-mobile-or-more-direction-column-reverse"]);
  props.isTabletOrLessDirectionColumnReverse && classNameList.push(classNames["is-tablet-or-less-direction-column-reverse"]);
  props.isTabletDirectionColumnReverse && classNameList.push(classNames["is-tablet-direction-column-reverse"]);
  props.isTabletOrMoreDirectionColumnReverse && classNameList.push(classNames["is-tablet-or-more-direction-column-reverse"]);
  props.isDesktopOrLessDirectionColumnReverse && classNameList.push(classNames["is-desktop-or-less-direction-column-reverse"]);
  props.isDesktopDirectionColumnReverse && classNameList.push(classNames["is-desktop-direction-column-reverse"]);
  props.isDesktopOrMoreDirectionColumnReverse && classNameList.push(classNames["is-desktop-or-more-direction-column-reverse"]);
  props.isWidescreenOrLessDirectionColumnReverse && classNameList.push(classNames["is-widescreen-or-less-direction-column-reverse"]);
  props.isWidescreenDirectionColumnReverse && classNameList.push(classNames["is-widescreen-direction-column-reverse"]);
  props.isWidescreenOrMoreDirectionColumnReverse && classNameList.push(classNames["is-widescreen-or-more-direction-column-reverse"]);
  props.isFullhdOrLessDirectionColumnReverse && classNameList.push(classNames["is-fullhd-or-less-direction-column-reverse"]);
  props.isFullhdDirectionColumnReverse && classNameList.push(classNames["is-fullhd-direction-column-reverse"]); 
  props.className && classNameList.push(props.className);

  return (
    <div
      {...assignedProps}
      className={classNameList.join(" ")}
    />
  );
}
